name: netcalc
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash -l {0}
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults, anaconda
          environment-file: netsci.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          activate-environment: netsci

      - name: build
        shell: bash -l {0}
        run: |
         mkdir build
         cd build
         cmake ..
          
          
