name: netcalc
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    container: dvcorg/cml-py3:latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
      - name: Install netcalc dependencies
        run: |
            conda install -c conda-forge swig boost numpy cmake pytest
      - name: build
        run: |
            mkdir build
            cd build
            cmake .. -DCONDA_DIR=$CONDA_PREFIX
            cmake --build . -j
            make python
      - name: ctest
        run: |
          cd build
          ctest
      - name: pytest
        run: |
            cd tests/cuarray/python
            pytest
            cd ../../netsci/python
            pytest
