name: netsci
on: [push]
jobs:
  run:
    runs-on: [self-hosted, gpu]
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup anaconda
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install netsci dependencies
        run: |
          conda install -c conda-forge swig boost numpy cmake pytest
      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCONDA_DIR=$CONDA_PREFIX
          cmake --build . -j
          make python
      - name: ctest
        run: |
          cd build
          ctest
      - name: pytest
        run: |
          cd tests/cuarray/python
          pytest
          cd ../../netsci/python
          pytest