name: netcalc
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash -l {0}
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults, anaconda
          packages: cmake, swig, pytest, doxygen, boost, numpy
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: base
      - name: build
        run: |
            mkdir build
            cd build
            cmake .. -DCONDA_DIR=$CONDA_PREFIX -DCUDA_ARCHITECTURE=52
            cmake --build . -j
            make python
      - name: ctest
        run: |
          cd build
          ctest
      - name: pytest
        run: |
          pytest
