name: netcalc
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash -l {0}
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults, anaconda
          environment-file: netsci.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          activate-environment: netsci

      - name: build
        shell: bash -l {0}
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'
          sudo apt-get update && sudo apt-get install -y cmake
          mkdir build
          cd build
          cmake ..
          
          
